# Open PHACTS platform, v2.1
# Docker Compose configuration
# https://docs.docker.com/compose/yml/
#
# Each entry below defines a docker container,
# some of which expose ports, e.g. this exposes
# the internal port 80 as port 3002 to the world:
#
# ports:
#   - "3002:80"
#
# To change the exposed port, change the number on the left
#
# Data is stored in Docker volumes, which by default would be
# managed by Docker, e.g. created within /var/lib/docker
# with a UUID.
#
# To use a different folder/partition, e.g. for backup purposes,
# speed or disk requirements, modify "volumes:" for the
# *data containers further down.
#

## NOTE: Be careful about indentation!

version: '2'
services:

  explorer:
    container_name: ops-explorer
    image: openphacts/explorer2
    ports:
      - "3001:3000"
    links:
      - api
    environment:
      # Use full URL for calling external service.
      # Use service name if calling another web service defined in this file.
      # Do NOT include a trailing /
      - API_URL=http://localhost:3002
    #restart: always

  api:
    container_name: ops-api
    build: linkeddataapi
#    image: openphacts/ops-linkeddataapi
    ports:
      - "3002:80"
    links:
      - ims
      - memcached
      - virtuoso:sparql
    environment:
      - CRS=https://ops2.rsc.org/ops
      - CONCEPTWIKI=http://www.conceptwiki.org/web-ws/concept
    #restart: always

  memcached:
    container_name: ops-memcached
    image: memcached
    #restart: always

  # SPARQL server
  virtuoso:
    container_name: ops-virtuoso
    mem_limit: 112G
    #image: stain/virtuoso
    build: virtuoso-ops
    ports:
      - "3003:8890"
      - "3011:1111"
    volumes_from:
      - virtuosodata
      - openphactsrdf
    #restart: always

  virtuosodata:
    container_name: ops-virtuosodata
    image: busybox
    volumes:
      # To specify alternative data folder, use instead:
      # - /media/big-SSD/virtuoso:/virtuoso
      - /srv/ops-data/virtuoso:/virtuoso

  ## Uncomment either the 'virtuosostaging' service to load data from a Virtuoso backup,
  ## or uncomment 'virtuosostagingrdf' and 'openphactsrdf' to load data from RDF files.
  ## Then run one of the following to get triples into Virtuoso:
  # docker-compose up -d virtuosostaging
  # docker-compose up -d virtuosostagingrdf

  ### Populate RDF from virtuoso backup download
  # virtuosostaging:
  #   container_name: ops-virtuosostaging
  #   build: virtuosodata-frombackup
  #   volumes_from:
  #     - virtuosodata
  #

  ### Load RDF files into Virtuoso
  virtuosostagingrdf:
    container_name: ops-virtuosostagingrdf
    build: virtuosodata-fromrdf
    links:
     - virtuoso
    volumes_from:
     - virtuosodata
     - openphactsrdf

  ### Download from data.openphacts.org
  openphactsrdf:
    container_name: ops-openphactsrdf
    image: busybox
#    build: openphacts-rdf
    volumes:
      - /srv/ops-data/download:/download
      - /srv/ops-data/staging:/staging
      # To specify alternative data folder, use instead:
      # - /media/big-SSD/download:/download
      # - /media/big-SSD/staging:/staging


  ims:
    container_name: ops-ims
    image: openphacts/identitymappingservice
    ports:
      - "3004:8080"
    links:
      - mysql
    #restart: always

  mysqlstaging:
    container_name: ops-mysqlstaging
    build: mysqlstaging
    #image: openphacts/identitymappingservice-staging
    links:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ims
      - MYSQL_USER=ims
      - MYSQL_PASSWORD=ims
      - MYSQL_ROOT_PASSWORD=uCie0ahgah
#      - MYSQL_ROOT_PASSWORD=tiger

  mysql:
    container_name: ops-mysql
    image: mysql:5.7
    volumes_from:
      - mysqldata
    environment:
#      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=ims
      - MYSQL_USER=ims
      - MYSQL_PASSWORD=ims
      - MYSQL_ROOT_PASSWORD=uCie0ahgah
    #restart: always

  mysqldata:
    container_name: ops-mysqldata
#     image: busybox
    image: ubuntu
    volumes:
       # To specify alternative data folder, use instead:
       # - /media/big-SSD/mysql:/var/lib/mysql
      - /var/lib/mysql

  ### END custom loading


  # For Open PHACTS version 2.1: includes Sure ChEMBL and additional Wikipathways data.

  ## Future services

  #elasticsearch:
  #  container_name: ops-elasticsearch
  #  image: elasticsearch
  #ops-search:
  # container_name: ops-search
  # image: openphacts/ops-search
  #ops.js
  #crs
